on: [push]

name: Linux_Node_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'ghatestappsb3'
    
    - name: Azure logout
      run: |
        az logout
